[Common]
# Default width of dialog window
Width=-1
# Default height of dialog window
Height=-1
# Borders around dialog
Border=5
# Show remaining time and percentage in timeout progress bar
ShowRemain=false
# Combo-box in entry dialog is always editable
ComboAlwaysEditable=false
# Default terminal command (use %s for arguments placeholder)
Terminal=xterm -e "%s"
# Default open command (use %s for arguments placeholder)
OpenCommand=xdg-open "%s"
# Default date format (see strftime(3) for details)
DateFormat=%x
# Default color for URI highlight in text-info dialog
URIColor=blue
# Maximum number of tabs in notebook dialog
MaxTab=100
# Use large previews in file selection dialogs)
LargePreview=false
# Set width of search entry in search bar
SearchWidth=100
# Ignore unknown command-line options
IgnoreUnknownOptions=true
# Enable debug mode with information about deprecated features
Debug=false

[SourceView]
# Default color theme for text-info dialog
Theme=
# Show line numbers
LineNum=false
# Highlight current line
LineHilite=false
# Enable line marks mode
LineMarks=false
# Default color for first type of text marks
Mark1Color=lightgreen
# Default color for second type of text marks
Mark2Color=pink
# Show right margin at position (0 to disable)
RightMargin=0
# Highlight matching brackets
Brackets=false
# Use autoindent
Indent=false
# Smart Home/End behavior (0 - never, 1 - before, 2 - after, 3 - always)
HomeEnd=0
# Use smart backspace
SmartBS=false
# Default tabulation width
TabWidth=8
# Default indentation width
IndentWidth=4
# Insert spaces instead of tabs
Spaces=true
